# Generated by Django 3.2.20 on 2023-08-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_areainfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=32)),
                ('abbreviation', models.CharField(max_length=32)),
                ('device_mold', models.CharField(max_length=32)),
                ('user_mold', models.CharField(max_length=32)),
            ],
        ),
    ]
